### PR TITLE
Remove stringr (which never worked anyway)

### PR DESCRIPTION
**Pull request by peterhurford**

### CODE REVIEW

**Comment by robertzk** [comment]
@peterhurford Maybe remove from DESCRIPTION file as well and re-run document()?

**Comment by peterhurford** [comment]
@robertzk stringr is not in the DESCRIPTION file.

**Comment by robertzk** [comment]
That's terrible. LGTM.

**Comment by peterhurford** [comment]
Per discussion will just remove this feature.

**Pull request closed without merging**
