### PR TITLE
S3read deserialize

### PR DESCRIPTION
**Pull request by tianzhan31**
@robertzk modified s3read by adding new argument serialize. Request to be merged to the master.

### CODE REVIEW

**Comment by robertzk** [comment]
Looks good, will merge when green.

**Comment by peterhurford** [comment]
@tianzhan31 @robertzk Can you up the version? :+1:

**Comment by tianzhan31** [comment]
@robertzk @peterhurford version incremented!

**Comment by davluangu** [comment]
:+1:

**Pull request merged**
